### ISSUE TITLE
new migration step

### ISSUE THREAD

**Issue by jurajsimbs** [BohemiaInteractive/bi-db-migrations#4]
so I have 1.0.0 migration commited/pushed
![image](https://user-images.githubusercontent.com/18613927/38133856-33c9cc20-3411-11e8-8cc6-e08d16400ae6.png)
then I want to create new mig. step so:  
- I pushed the version to 1.0.1 & run  
`node_modules/.bin/bi-db-migrate init:migration`  
it created a news step 1.0.1 but with the exact same content as was in 1.0.0 (maybe I need to run another command?) I thought that if I did not change anything from v1.0.0 next step will be empty or I'll get a warning or something...  
(maybe I need to tag version 1.0.0?)  
  
...also there is no description anywhere how to create js step?

**Comment by fogine** [comment]
> maybe I need to tag version 1.0.0

You've just answered the question. In order to create valid `1.0.1` migration, you need to release `1.0.0` first which includes creating a git release tag.

**Comment by fogine** [comment]
> and the other one:
"...also there is no description anywhere how to create js step?"


You're right that's not clear from the docs... You basically can do:

```bash
> bi-db-migrate init:migration --help
```

Will mention that. Thank you.
